package rs.util

import java.util.function.IntFunction

object KNOWN_NAMES : List<String> by listOf(
    // title
    "index.dat",
    "logo.dat",
    "p11.dat",
    "p12.dat",
    "b12.dat",
    "q8.dat",
    "runes.dat",
    "title.dat",
    "titlebox.dat",
    "titlebutton.dat",
    // seen in 274
    "p11_full.dat",
    "p12_full.dat",
    "b12_full.dat",
    "q8_full.dat",

    // config
    "flo.dat",
    "flo.idx",
    "idk.dat",
    "idk.idx",
    "loc.dat",
    "loc.idx",
    "npc.dat",
    "npc.idx",
    "obj.dat",
    "obj.idx",
    "seq.dat",
    "seq.idx",
    "spotanim.dat",
    "spotanim.idx",
    "varp.dat",
    "varp.idx",
    // seen in 254
    "varbit.dat",
    "varbit.idx",
    // seen in 274
    "mesanim.dat",
    "mesanim.idx",
    "mes.dat",
    "mes.idx",
    "param.dat",
    "param.idx",
    "hunt.dat",
    "hunt.idx",

    // interface
    "data",

    // media
    "backbase1.dat",
    "backbase2.dat",
    "backhmid1.dat",
    "backhmid2.dat",
    "backleft1.dat",
    "backleft2.dat",
    "backright1.dat",
    "backright2.dat",
    "backtop1.dat",
    "backvmid1.dat",
    "backvmid2.dat",
    "backvmid3.dat",
    "chatback.dat",
    "combatboxes.dat",
    "combaticons.dat",
    "combaticons2.dat",
    "combaticons3.dat",
    "compass.dat",
    "cross.dat",
    "gnomeball_buttons.dat",
    "headicons.dat",
    "hitmarks.dat",
    "invback.dat",
    "leftarrow.dat",
    "magicoff.dat",
    "magicoff2.dat",
    "magicon.dat",
    "magicon2.dat",
    "mapback.dat",
    "mapdots.dat",
    "mapfunction.dat",
    "mapscene.dat",
    "miscgraphics.dat",
    "miscgraphics2.dat",
    "miscgraphics3.dat",
    "prayerglow.dat",
    "prayeroff.dat",
    "prayeron.dat",
    "redstone1.dat",
    "redstone2.dat",
    "redstone3.dat",
    "rightarrow.dat",
    "scrollbar.dat",
    "sideicons.dat",
    "staticons.dat",
    "staticons2.dat",
    "steelborder.dat",
    "steelborder2.dat",
    "sworddecor.dat",
    "tradebacking.dat",
    "wornicons.dat",
    "backtop2.dat",
    "mapflag.dat",
    "mapmarker.dat",
    "mod_icons.dat",
    "mapedge.dat",
    "blackmark.dat",
    "button_brown.dat",
    "button_brown_big.dat",
    "button_red.dat",
    "chest.dat",
    "coins.dat",
    "headicons_hint.dat",
    "headicons_pk.dat",
    "headicons_prayer.dat",
    "key.dat",
    "keys.dat",
    "leftarrow_small.dat",
    "letter.dat",
    "number_button.dat",
    "overlay_duel.dat",
    "overlay_multiway.dat",
    "pen.dat",
    "rightarrow_small.dat",
    "startgame.dat",
    "tex_brown.dat",
    "tex_red.dat",
    "titlescroll.dat",

    // models
    "base_head.dat",
    "base_label.dat",
    "base_type.dat",
    "frame_del.dat",
    "frame_head.dat",
    "frame_tran1.dat",
    "frame_tran2.dat",
    "ob_axis.dat",
    "ob_face1.dat",
    "ob_face2.dat",
    "ob_face3.dat",
    "ob_face4.dat",
    "ob_face5.dat",
    "ob_head.dat",
    "ob_point1.dat",
    "ob_point2.dat",
    "ob_point3.dat",
    "ob_point4.dat",
    "ob_point5.dat",
    "ob_vertex1.dat",
    "ob_vertex2.dat",

    // versionlist
    "anim_crc",
    "anim_index",
    "anim_version",
    "map_crc",
    "map_index",
    "map_version",
    "midi_crc",
    "midi_index",
    "midi_version",
    "model_crc",
    "model_index",
    "model_version",

    // textures
    *Array(50) { "$it.dat" },

    // wordenc
    "badenc.txt",
    "domainenc.txt",
    "fragmentsenc.txt",
    "tldlist.txt",

    // sounds
    "sounds.dat",

    // worldmap
    "labels.dat",
    "floorcol.dat",
    "underlay.dat",
    "overlay.dat",
    "size.dat") {

    override fun <T : Any?> toArray(generator: IntFunction<Array<out T?>?>): Array<out T?>? {
        return super.toArray(generator)
    }
}